# Generated by Django 5.0.4 on 2024-06-17 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentform',
            name='card_type',
            field=models.CharField(choices=[('debit', 'Debit'), ('credit', 'Credit')], max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='paymentform',
            name='cvv',
            field=models.IntegerField(max_length=4, null=True),
        ),
        migrations.AlterField(
            model_name='paymentform',
            name='card_number',
            field=models.IntegerField(max_length=16, null=True),
        ),
    ]
