# Generated by Django 5.0.4 on 2024-06-18 15:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0002_paymentform_card_type_paymentform_cvv_and_more'),
        ('rentals', '0003_alter_rental_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentform',
            name='rental',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='rentals.rental'),
        ),
        migrations.AlterField(
            model_name='paymentform',
            name='card_number',
            field=models.BigIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='paymentform',
            name='cvv',
            field=models.IntegerField(null=True),
        ),
    ]
