# Generated by Django 5.0.4 on 2024-06-18 15:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0003_paymentform_rental_alter_paymentform_card_number_and_more'),
        ('rentals', '0003_alter_rental_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentform',
            name='rental',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='rentals.rental'),
        ),
    ]
