# Generated by Django 5.0.4 on 2024-06-17 02:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rentals', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='rental',
            name='pickup_time',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='rental',
            name='return_time',
            field=models.DateTimeField(null=True),
        ),
    ]
