# Generated by Django 5.0.4 on 2024-06-18 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rentals', '0002_rental_pickup_time_rental_return_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rental',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
