# Generated by Django 5.0.6 on 2024-06-23 04:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rentals', '0003_alter_rental_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rental',
            name='pickup_time',
            field=models.TimeField(null=True),
        ),
        migrations.AlterField(
            model_name='rental',
            name='return_time',
            field=models.TimeField(null=True),
        ),
    ]
